### PR TITLE
 added front light

### PR DESCRIPTION
**Pull request by meguiraun**
and fixes with the get_status if a motor is not present. Note that I renamed the api calls for the On/off.

We slightly changed the names of the roles (wagobacklight, backlight, wagofrontlight, frontlight) which might have effect in your tests, see SampleCentring.py#L419

### CODE REVIEW

**Comment by mguijarr** [comment]
Why role names have been changed? I don't like the 'wago' prefix, it seems too much specific for a kind of hardware

**Comment by meguiraun** [comment]
there were changed to give them a more meaningful name, also to clearly differentiate back and front light md motors. Does it cause any trouble to you? 

We can remove the 'wago' prefix for something else.

**Comment by meguiraun** [comment]
I think I misunderstood your objections... Will this PR be accepted if I switch back to the original role names? Or it is enough if I remove the 'wago' keyword?

**Comment by mguijarr** [comment]
Hi Mikel,
Sorry I forgot about this PR... Indeed, I think it would be great to remove the "wago" prefix.
Then I would happily accept it ;)

**Comment by meguiraun** [comment]
No sorries, too many things to do during a shutdown! 
I renamed as 'backlightswitch', etc. Hope it makes sense.

**Comment by beteva** [comment]
Hello,
seems to me something have been lost, as I have changed wago to actuator some time ago. There is an in/out hardware object, which deals with that and the respective calls in some bricks.

**Comment by meguiraun** [comment]
We are using the MicrodiffInOut hwobj, this was only related to the name of the role. Clearly a bad renaming since it has added more confusion... sorry about that.

**Pull request merged**
