### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hi 

These are some minor fixes that we have applied during the last two-three weeks of operation. Its mostly related to how samples are handled in the sample grid when collected, or when lims is synchronized.

Apart from that some fixes to the group path, and added path validation.

The commits are otherwise rather atomic, and I think the commit messages says whats done.

Cheers,
Marcus

### CODE REVIEW

**Comment by meguiraun** [comment]
tack for this, I will try to review during the day

**Comment by meguiraun** [comment]
I understand the point, but this modal is the only way of preventing the user to click in wrong places (send another command to the sc, move any motor, etc.).

**Comment by marcus-oscarsson** [comment]
Ok, the users and scientist have found it quite useful here so I hope its the same for you ...

**Comment by meguiraun** [comment]
Hi @marcus-oscarsson, our scientist did not like the idea at all. They do not want any mistake by a user by hitting anything on the sample changer, queue and so on.

Could you remove this commit from this PR so I accept it? And then we can discuss further during next meeting how to deal with the blocking in a way that fits both sites? What do you think?

mikel

**Comment by marcus-oscarsson** [comment]
I would rather like to keep this as it is until we have decided what to do.

**Comment by meguiraun** [comment]
Ok, as you prefer. I will try to deploy your branch and give to our scientist so they have a better feeling on the implications

**Comment by marcus-oscarsson** [comment]
Added a few other fixes:

 - Replacing all colons (:) with dashes (-) in path to avoid need for escaping the path and for making it possible for certain software to even read the data.

 - Opening the sample link in a new tab

 - Prepared for server side generation of the ISPyB results, to make it possible to integrate already existing result views from lims directly in MXCuBE and to make the the result part less dependent on lims flavor.

**Comment by marcus-oscarsson** [comment]
Hi,

I've made a few more commits as you can see, all related to not allowing "special" characters in the paths and improving the lims result display.

We had a short discussion here and I've made the SC dialog blocking again since it is the most common solution, that require least changes on both sides.

Cheers,
Marcus

**Pull request merged**
