### PR TITLE
Issue #538: Duplicate a task

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hi 

  - Added the possibility to duplicate tasks, implementing #538 

Marcus

### CODE REVIEW

**Comment by meguiraun** [comment]
thanks for this, however I am having some issues:

When I try to add a sample:
```
2017-08-23 14:07:11,199 |exceptions|ERROR  | Uncaught exception while calling /mxcube/api/v0.1/queue
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mxcube/mxcube3/mxcube3/routes/Queue.py", line 225, in queue_add_item
    tindex_list = task["parameters"].get("taskIndexList", False)
KeyError: 'parameters'
```
But... it is actually added to the queue ??!@@!@!! I see it calling the api for getting the queue, also when refresh it appears in the interface.

Also, I see several messages like this one in the browser console (in Chrome and Firefox):
```
 error      TypeError: this.canvas.getActiveGroup is not a function
    at SampleImage.renderSampleView (main.js:132170)
    at SampleImage.componentDidUpdate (main.js:131733)
    at measureLifeCyclePerf (main.js:195140)
    at main.js:195794
    at CallbackQueue.notifyAll (main.js:102234)
    at ReactReconcileTransaction.close (main.js:200235)
    at ReactReconcileTransaction.closeAll (main.js:52262)
    at ReactReconcileTransaction.perform (main.js:52209)
    at ReactUpdatesFlushTransaction.perform (main.js:52196)
    at ReactUpdatesFlushTransaction.perform (main.js:7013)
```
After SET_INITIAL_STATE, BL_ATTR_GET_ALL, SET_CURRENT_SAMPLE, START_CLICK_CENTRING... So I cannot do the centring and thus cannot add a task to duplicate...

**Comment by marcus-oscarsson** [comment]
The last two commits hopefully solves the issues you get, thanks

**Comment by marcus-oscarsson** [comment]
For this error:
  `TypeError: this.canvas.getActiveGroup is not a function`

Its not related to this PR. It seems like fabric have been updated and the function getActiveGroup
have been removed. So we have to cope with that !

Marcus

**Comment by marcus-oscarsson** [comment]
It seems like the latest stable version of fabric is 1.7.17 so use that and it should work fine. The 2.0.0-beta seems to have some issues.

Marcus

**Comment by meguiraun** [comment]
thanks for the fixes

**Pull request merged**
