### PR TITLE
Store reorganization

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Dear all,

So here is the re-organization of the store that I described in issue #305. I have not yet moved motors from sampleView to beamline.

The list of samples (sampleList) and manulMount  have been moved from SamplesGrid to queue. The data structure of the queue was partially changed by a previous merge of a incomplete PR. This broke the queue related features as Fredrik noticed, we are sorry for this glitch. The queue data structure have been fixed and should now be working fine.

I have tested as much as I can here, adding samples and tasks. Moving the Tasks around, editing and removing them. These changes are reflected both in the SampleView and in the SampleGrid so everything seems to work fine.

However, testing with the latest master is impossible because the centering and adding tasks does not work properly. See issue #309 for more details.

I would have liked to move the motors and clean up the queue reducer a bit before doing this PR. But I would like to sort out the issues in #309 before so that I can be certain that what I did works with the latest master. So Ill mark this as WIP.

Cheers,
Marcus

### CODE REVIEW

**Comment by mguijarr** [comment]
Issue #309 is probably solved now thanks to latest PR by Mikel.

I am leaving on holidays so Marcus will accept PRs for the next 2 weeks for ESRF.

**Comment by marcus-oscarsson** [comment]
Hi, 

So I'm finally finished with this I have tested against the latest master and it seems to work fine. I finally moved the motors to the beamline store as well. Doing this I noticed that pixelsPerMm is communicated through the motors update, but I kept pixelsPerMm in the sampleview since the rest of the camera related things are there. It somehow makes more sense to keep pixelsPerMm in sampleview, especially for debugging. Please let me know if you are of another opinion ? 

In anyways I noticed that the pixelsPerMm is sent with the Camera object at SET_INITIAL_STATUS in
/reducers/sampleview.js. Why is it that its sent with the camera in the beginning and then with the
motors ?.

Marcus

**Comment by bolmsten** [comment]
Great work, I see that this is a big one! 

I will begin testing today but as a first thing I noticed that "UPDATE_TASK" does not work anymore it seems to have gotten lost in the refatoring between samplegrid and queue?

**Comment by bolmsten** [comment]
"Why is it that its sent with the camera in the beginning and then with the
motors ?" 

This is to reduce the amount of actions when updating from the socketIO, it probably should be refactored someway.

**Comment by marcus-oscarsson** [comment]
Okey, I see so its for optimization then. I noticed that motors are already present in action.data 
so I though there was another issue more related to the server. Just a question mostly out of curiosity, I guess its fine as it is.

**Comment by marcus-oscarsson** [comment]
Good catch, it seems like UPDATE_TASK reducer was lost. Maybe it went on 
vacation with Matias :). Ill make a fix asap.

**Comment by marcus-oscarsson** [comment]
Ive added the missing UPDATE_TASK reducer and made the necassary changes to the API. Updating a task should work fine now :)

Good evening :)

**Comment by bolmsten** [comment]
Hi we have continued testing and see that when changing tasks and going back the button wrongly says "add task" instead of "change". 

We also had some problem running before but are having problems recreating that issue

**Comment by bolmsten** [comment]
Minor linting errors also appears

**Comment by marcus-oscarsson** [comment]
Thanks for the testing I know that its tedious, and its Friday too :)

Okey, Ill take a look at the problem with "add task" instead of "change". How did you get that ?, did you have some errors in the Console ?

Marcus

**Comment by marcus-oscarsson** [comment]
Okey, so the latest commit should resolve the "add task" displayed instead of "change" problem.

**Comment by bolmsten** [comment]
@marcus-oscarsson 

Good, I see that you have fixed it now. 

We will do one last test today to see that everything is working but by looking at the code it seems to me that "ADD_TASK_RESULT" should fail as it uses the old structure, do you agree? As I said we did not manage to test this the last time and will do so later today.

**Comment by bolmsten** [comment]
Also regarding the new structure do you want to save task not on the samplelist but instead on the queue? 

If I understood your suggestion from before everything should be on the samplelist? This would make it easier to take the state from the server and give the client, presuming that the server outputs in the same form.

**Comment by marcus-oscarsson** [comment]
Good morning !

Your right the ADD_TASK_RESULT might not be updated to the new structure of the queue. Ill take a look at it.

The new structure of the queue is a mix of what I had in the SampleGrid and what you were using in the queue and might honestly not be the final structure.  The main goal of this PR was the reorganization of the stores. I did some compromises to make the PR easier to handle and to at get it to work. For instance the queue is still accessed by queue ids which I would like to avoid in the future, I'm sure we will continue to exchange ideas to converge to something great :). 

The main idea with this representation of the queue is that its easy to read and thus to debug and hopefully to extend. We also hope that we can reduce the logic needed to manipulate the queue although this of course depends on how the queue is exchanged between the server and client. I know that it costs us time and effort now (and its definitely not the most fun thing to do) but I hope that it will save us time later.

The separation of samplelist and queue is done by purpose since we might have samples which are not necessarily in the queue. I see the queue as something that we want to collect on and the samplelist is just the list of potential samples to collect on. But there is perhaps a better structure ?

Cheers,
Marcus

**Comment by bolmsten** [comment]
Great! 

I totally agree with your suggestion about taking it in steps and this would be the first one.  
I think the next step would be to refactor all node_ids to sampleID both in client and API.

**Comment by marcus-oscarsson** [comment]
:)

That's a good idea, your right I think its enough to send sampleIDs between the client and server. I'm looking into the next refactoring and I have not decided exactly how to do it yet. I'm still working on the idea of sending the entire queue but its not finished yet, I have some code but its far from finished. But the sampleID refactoring is maybe a good start.

M

**Comment by marcus-oscarsson** [comment]
So the last commit should fix ADD_TASK_RESULT, it seems to work fine here as well. I first though that was handled by UPDATE_TASK so I completely missed it, sorry about that.

**Pull request merged**
