### PR TITLE
Dependencies and docker build in Travis

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hi,

Just remove unused canvas dependency

Marcus

### CODE REVIEW

**Comment by meguiraun** [comment]
Tried running with mockups:
```
2018-12-07 12:32:50,107 |exceptions|ERROR  | Uncaught exception while calling /mxcube/api/v0.1/sampleview/camera
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mxcube/mxcube3/mxcube3/core/loginutils.py", line 119, in wrapped
    return f(*args, **kwargs)
  File "/mxcube/mxcube3/mxcube3/routes/samplecentring.py", line 72, in get_image_data
    data = beamlineutils.get_viewport_info()
  File "/mxcube/mxcube3/mxcube3/core/beamlineutils.py", line 153, in get_viewport_info
    width, height, scale = streaming.video_size()
  File "/mxcube/mxcube3/mxcube3/video/streaming.py", line 71, in video_size
    scale = float(current_size[0]) / VIDEO_ORIGINAL_SIZE[0]
ZeroDivisionError: float division by zero
```
any idea?

**Comment by marcus-oscarsson** [comment]
Yes, what is streaming.video_size() returning or is VIDEO_ORIGINAL_SIZE[0] 0 perhaps ?

**Comment by marcus-oscarsson** [comment]
I guess its because you are not using streaming ...

**Comment by marcus-oscarsson** [comment]
Its not related to this PR but I included a fix for it

**Comment by meguiraun** [comment]
Thanks. yes, but do you test with mockups or with your hardware?
I will accept as soon as travis finishes

**Comment by marcus-oscarsson** [comment]
Always both, with a few exceptions ..

**Pull request merged**
