### PR TITLE
Improve handling of session timeout

### PR DESCRIPTION
**Pull request by fabcor-maxiv**
GitHub: related to https://github.com/mxcube/mxcubeweb/issues/1032
GitHub: related to https://github.com/mxcube/mxcubeweb/pull/1036

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson @elmjag 

Ready for review and merge.

All the current authentication tests are only run against the proposal-based authentication. In the next step, my goal is to run all those tests against both proposal-based and user-based authentication.

**Comment by fabcor-maxiv** [comment]
I put it back as draft, while I investigate a potential issue. Something might be off, or maybe I am just misunderstanding things.

@marcus-oscarsson @elmjag @meguiraun 
When exactly is the session supposed to expire? After 1 minute of inactivity, is that right? But the expiration timestamp in the cookie is way off (100 minutes)... I am confused.

**Comment by marcus-oscarsson** [comment]
Hey @fabcor-maxiv I noticed that the session time seems to be in UTC (offsetted by two hours) is that what you noticed. It otherwise seems to be updated correctly so that its valid for one minute

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson @elmjag @meguiraun 

I investigated, and it was my misunderstanding.

I also thought about time zone issues at first, but it was not the case.

What happened is that I had started mxcube with different settings than I had earlier (our real settings instead of the the default mockup settings), so I was not seeing what I was expecting to see, even though what I was seeing was perfectly correct.

I will add these latest findings to the `Login.rst` doc.

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson @elmjag @meguiraun

Documentation updated.

PR is ready for review and merge.

**Comment by marcus-oscarsson** [comment]
Great :), thanks

**Comment by marcus-oscarsson** [comment]
Very nice, well done !

**Pull request merged**
