### PR TITLE
setup.py script to install MXCuBE 3

### PR DESCRIPTION
**Pull request by mguijarr**
renamed mxcube.py to mxcube3, installs as a script
generated MANIFEST file (python setup.py sdist)
added requirements.txt

### CODE REVIEW

**Comment by meguiraun** [comment]
Can we add the following to mxcube3 launcher file so we do not need to do an install to run the server:
```python
try:
    from mxcube3 import app, socketio
except:
    from src import app, socketio
```
Or anything more elegant if you prefer.

**Comment by mguijarr** [comment]
We may want to rename `src` to `mxcube3` instead of doing the `try...except` thing ?
It has implications on the submodules (that would need to be reinitialized)
If you think it's a good idea I can do it otherwise if you prefer the `try...except` just do it :)

**Comment by meguiraun** [comment]
let's go with the simplest solution, renaming is enough. thanks

**Comment by mguijarr** [comment]
I did the change, I renamed `src` to `mxcube3`, and so the `mxcube3` script is renamed `mxcube3-server`. However I can't make the pull request while my other PR is pending. I will do it as soon as the previous PR gets accepted.

**Comment by amilan** [comment]
PR accepted!! You are free to continue ;)

**Comment by mguijarr** [comment]
Thanks :)
In fact, it's already all done, there is some magic I can't explain: the PR from yesterday got updated with latest master from my fork, and so latest changes we were talking about in this thread are
already merged.
Perfect, but weird... Anyway.

**Pull request merged**
