### PR TITLE
Check MIME type before parsing responses as JSON

### PR DESCRIPTION
**Pull request by axelboc**
Addresses https://github.com/mxcube/mxcubeweb/issues/1355#issuecomment-2306379987

I was able to write a wretch add-on for this, which is pretty awesome. :tada: The add-on adds a method called `expectJson` to wretch's chainable API (more specifically to the response chain, so after `get`, `post`, etc.)

So you can now do: `.get(...).expectJson().json()` and you'll see something like this:

image

You have to go down the stack trace a bit to find the location of the problematic fetch call, but I think that's okay.

### CODE REVIEW

**Comment by elmjag** [comment]
Is it possible to include call do the json parsing inside the `expectJson` function?

It would be nice if we could just do:

`return endpoint.get('/beam/info').expectJson();`

**Comment by axelboc** [comment]
Even better, thanks :+1: 

I called it `safeJson`, though.

**Review by elmjag — APPROVED** [review]

**Comment by marcus-oscarsson** [comment]
Nice

**Comment by marcus-oscarsson** [comment]
Thanks @elmjag and @axelboc

**Pull request merged**
