### PR TITLE
Styling

### LINKED ISSUE #769: Noise overlay still visible in help
Hi,

The "noise" overlay used for remote access is still visible in the help, but controls displayed on top.
Remove the noise overlay completely from the help page if the help page is needed in observer mode.

### PR DESCRIPTION
**Pull request by meguiraun**
Few things:
* Display a icon next to a input field when error or warning with tooltip message
image
image
* Add site specific links to the Help pages (defaults provided)
* fix #769

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Looks really nice :) !, what do you think about adding some more space between the icon and the input ?

**Comment by meguiraun** [comment]
will try but there is not much space left without modifying all col-xx stuff

**Comment by meguiraun** [comment]
lets see now
image

**Comment by marcus-oscarsson** [comment]
Thanks !

**Comment by marcus-oscarsson** [comment]
Its nice, lets tweak it later :)

**Pull request merged**
