### PR TITLE
Fix for issue #381

### PR DESCRIPTION
**Pull request by mguijarr**
* rate limitation decorator now drops events received in the delay interval
* motor states are handled individually (like motor positions since #373)
* as a consequence, `signals.microdiffSignals` and `motor_signals` have been purged from
position and state signals
* CSS transition duration for motor states is 300 ms now instead of 1 s

We tested this on ID30A3 just now.

### CODE REVIEW

**Comment by meguiraun** [comment]
Wow, that was fast! We will test tomorrow morning! Thanks

**Comment by meguiraun** [comment]
almost there. It has been improved but now we drop the last signal as well, so it happens that the final position is never updated (until any future emit on such motor).

**Comment by mguijarr** [comment]
Ah ah. Sorry.

When I first tried to fix it there was still the big thing that sends all signals at a state change, and I relied on this behavior to make sure last position was up-to-date.

But then I decided to further optimize states too and I removed `motor_event_callback` for state updates, and it leads to the bug you describe.

I am going to fix it pretty soon :) Sorry for the inconvenience.

By the way, this is what I called "handling motors individually" in the list of issues I sent last time.

**Comment by mguijarr** [comment]
Can you try now, Mikel ?

**Comment by meguiraun** [comment]
sorry, beamline busy.... I will test tomorrow morning. Thanks.

**Pull request merged**
