### PR TITLE
Tests and travis CI integration

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hi

 - Fixed the tests after the latest changes which broke the login from tests so all tests were failing.
 - Added draft travis.yml for travis integration currently with python 3 as well, only configured the backend part so far.

This PR is dependent on PR #267 of HR

Cheers
Marcus

### CODE REVIEW

**Comment by meguiraun** [comment]
test failed :)!! happy not for the fail, but for the CI you set up, great!

**Comment by marcus-oscarsson** [comment]
So we can merge this then ?

**Comment by meguiraun** [comment]
I am  missing sth, I can merge ... but test are failing, should not fix that before merge?

**Comment by marcus-oscarsson** [comment]
We are also testing python 2.7 - 3.7 so that's another reason for that the tests are failing, but I have another PR waiting for that :). All tests except 7 queue tests pass for python 2.7 on my account, so it should be the same here. We have to take a look the 7 failing tests separably.

**Comment by meguiraun** [comment]
ahahaha, ok.

**Pull request merged**
