### PR TITLE
Worklfow dialog return

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hey

Some more workflow features implemented,

 - Sending back parameters entered in the generic workflow parameters dialog
 - Minor fixes in dialog display related code

It should now be possible to run all workflows that are not using result overlays.

Marcus

### CODE REVIEW

**Comment by meguiraun** [comment]
Hej @marcus-oscarsson,
I cannot launch normal data collections, I get:
```
2017-03-23 18:57:06,093 |INFO   | Calling execute on: <DataCollectionQueueEntry object at 0x2623750> []
Traceback (most recent call last):
  File "/mxcube/mxcube3/mxcube3/HardwareObjects/queue_entry.py", line 829, in collect_dc
    self.collect_hwobj.set_mesh(False)
  File "/mxcube/mxcube3/mxcube3/HardwareRepository/BaseHardwareObjects.py", line 330, in __getattr__
    raise AttributeError(attr)
AttributeError: set_mesh
```
Tested both auto and manual samples. Latest 2.2 hwobj. Which version are you using for testing? Am I missing something?

**Comment by marcus-oscarsson** [comment]
Hey Mikel,

We are using 2.2 so that should not be a problem, Which Collect HW Object are you using ?

Marcus

**Comment by marcus-oscarsson** [comment]
Okey, So I looked a bit deeper. It looks like someone added set_mesh to DataCollectionQueueEntry a while a go and did not add the corresponding definition to MultiCollectMockup. So It wont work on any MxCuBE 3 version using MultiCollectMockup.

Ive made a PR to fix (HardareObjects), so It have nothing really to do with this PR :)

Marcus

**Comment by meguiraun** [comment]
Sorry @marcus, I was looking at the PR list and I saw this still pending.

**Pull request merged**
