### PR TITLE
Separate log formatter for terminal and file

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Separate log-formatter for terminal and file, so that the file does not end up with color coding.

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
The pages build sometimes fails with some strange micromamba error, any ideas ?

**Comment by fabcor-maxiv** [comment]
> The pages build sometimes fails with some strange micromamba error, any ideas ?

@marcus-oscarsson Where? Do you have a link to a failing job?

**Comment by marcus-oscarsson** [comment]
Hey, working late I see ;), here you go https://github.com/mxcube/mxcubeweb/actions/runs/6576746692/job/17866831451. But this one is different from the ones I had previously

**Comment by marcus-oscarsson** [comment]
This was probably another problem, I sometimes get a micromamba error at the install step, it seems like it works with just triggering the job again so its not a biggie.

**Comment by fabcor-maxiv** [comment]
@marcus-oscarsson 

> https://github.com/mxcube/mxcubeweb/actions/runs/6576746692/job/17866831451

In this case it was during a "post setup" step which I have no control over :/


> it seems like it works with just triggering the job again so its not a biggie

Oh, good, but yes feel free to ping me if it happens again especially if it ever gets to a case where it is blocking work :)

**Comment by marcus-oscarsson** [comment]
Yeah, as I said its not a big issue. Thanks for having a look

**Pull request merged**
