### PR TITLE
missing deps

### PR DESCRIPTION
**Pull request by meguiraun**
@rhfogh f90nml seems needed for GP workflows, I just picked latest version

### CODE REVIEW

**Review by rhfogh — COMMENTED** [review]
Do we need those in mxcubeweb? All three are in the mxcubecore pyproject.toml, near as I can see. As indeed are e.g. Python, gevent, and pydantic, so coudl we get rid of (some of) those? I'd say that it was better to have dependencies only in mxcubecore, even as a general principle (a unique source of truth), but certainly for py4j and f90nml that are only used in mxcubecore.

**Comment by meguiraun** [comment]
mmm... then a fresh conda env + poetry did not install those

**Comment by meguiraun** [comment]
I could not reproduce the issue anymore  🤨... I removed duplicated deps

**Comment by meguiraun** [comment]
I also updated the wiki [section 5](https://github.com/mxcube/mxcubeweb/wiki#installing-using-conda)

**Comment by marcus-oscarsson** [comment]
Well done, I also agree that we don't should not duplicate those dependencies. Great :1st_place_medal:  for updating the wiki !

**Pull request merged**
