### PR TITLE
fix for the first call to login_info

### PR DESCRIPTION
**Pull request by meguiraun**
solving #584

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Hey Mikel !

This probably solves the problem of proposal_list not being defined but it suggest that select_proposal
must be called in a certain order dependent of some other logic. Id prefer if proposal_list was properly
defined so that we always can call select_proposal with a deterministic result.

Whats your opinion on that, am I somehow mistaken ?

Marcus

**Comment by meguiraun** [comment]
The select proposal is only called after a successful login. The first call to `login_info` does nothing, then `login` is successful and then, the next call to `login_info` does the select_proposal. It assumes that a user/proposal has logged in successfully, if not, it should not be executed.

I do not fully grasp what you mean, perhaps the current order is a bit messy and we just need to put some better order? Or you prefer that we always call it `set_proposal` but it checks the login state itself?

I would suggest to accept this pr, since it essentially solves the issue. We can discuss tomorrow any improvement on the login flow. Would that be ok? I am not against your idea, but I think it needs a bit of discussion, and the refactoring can be a bit tricky.

**Comment by marcus-oscarsson** [comment]
What I don't find very appealing is that we get an attribute error (that is we have a variable that is not defined) if we don't execute things in a certain order or context. So we will probably need to change that at the time when or if we move the call to select_proposal. 

The solution would simply be to define the selected_porposals list in the right place

**Comment by meguiraun** [comment]
with this fix the attribute error disappears, you will not access that variable if the conditions are not meet.

**Pull request merged**
