### PR TITLE
WIP Light version

### PR DESCRIPTION
**Pull request by bolmsten**
Hi @mguijarr  @marcus-oscarsson ,

As discussed at the workshop a light version of MXCuBE should be developed for Maxlab. Here is my first try at a "light" version and would appreciate input and thoughts.

/ Fredrik

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Hey !

Great work, it looks really nice :)  :+1: I personally like that the menu is to the left, we could perhaps even make it "hideable" at some point. We should perhaps avoid having two menus, we should either have a menu at the top or to the left but not both. But perhaps you have a different intention with the top menu ? I'm personally in favor of the left :), for the the simple reasons that it gives the application a more web application like "feel" and that most monitors today are wide rather than high. 

Something that I believe is important if we go for the menu on the left is that we have clear tooltips or even overlays that explain what each menu option does (since there is no title). By the way what is the garbage can icon  for ;).

It's maybe not completely done yet but I tried to add a sample with the new sample button but nothing  was added. I get the dialog with name and acronym but after that nothing. Just wondering if its supposed to work or not :)

Another question do you get the context menu on the mockup video ?

Keep up the good work,
Marcus

**Comment by bolmsten** [comment]
Thanks for the feedback @marcus-oscarsson ,

Regarding the two menus I agree with you and I initially had removed it from the top but there was a need to display information such as username( and in the future who is "master" ) in the top menu. We can try to figure out a better solution maybe. 

The trash can is just a reset as before and is only there under development. 

Regarding the adding samples I think Mikel maybe has changed somethings and I have not the latest server.

I do get the context menu on the mockup video and I hope that you are able to as well over a point?

**Comment by marcus-oscarsson** [comment]
I'm sure that we can find another way of displaying the user information and the remote mode. Not having thought  to much about it: one way to display master or slave would be to color code the menu depending on the mode. Maybe also adding it to the tittle of the page together with the user information ? Just some quick ideas :)

A the trash can is the reset, useful to know ;)

Hm, neither the add sample nor the context menu worked for me. I was not able to perform three click centering. I get the yellow cross but it gets stuck after the first click. The server log gives me this when doing 3-click: I don't know if is of any help, I guess its all fine if it works on your side. I'm
using version 2.2 of the HW-Objects.

```
* [HWR] INFO 2016-05-18 16:00:42,207 A click requested, x: 362.807852966, y: 346.842105263
* [HWR] DEBUG 2016-05-18 16:00:42,208 [TASK CALLBACK]
* [HWR] DEBUG 2016-05-18 16:00:42,208 [TASK CALLBACK]   {'Sample': '0:0', 'QueueId': 0, 'Signal': 'centringMoving', 'Message': 'Centring position moving', 'State': 1}
* [HWR] ERROR 2016-05-18 16:00:42,208 error sending message: {'Sample': '0:0', 'QueueId': 0, 'Signal': 'centringMoving', 'Message': 'Centring position moving', 'State': 1}
* [HWR] DEBUG 2016-05-18 16:00:42,208 [TASK CALLBACK]
* [HWR] DEBUG 2016-05-18 16:00:42,208 [TASK CALLBACK]   {'Sample': '0:0', 'QueueId': 0, 'Signal': 'centringSuccessful', 'Message': 'Centring procedure finished successfully', 'State': 2}
* [HWR] ERROR 2016-05-18 16:00:42,208 error sending message: {'Sample': '0:0', 'QueueId': 0, 'Signal': 'centringSuccessful', 'Message': 'Centring procedure finished successfully', 'State': 2}
* [HWR] DEBUG 2016-05-18 16:00:42,208 [TASK CALLBACK]
* [HWR] DEBUG 2016-05-18 16:00:42,208 [TASK CALLBACK]   {'Sample': '0:0', 'QueueId': 0, 'Signal': 'centringAccepted', 'Message': 'Centring position accepted', 'State': 2}
* [HWR] ERROR 2016-05-18 16:00:42,209 error sending message: {'Sample': '0:0', 'QueueId': 0, 'Signal': 'centringAccepted', 'Message': 'Centring position accepted', 'State': 2}
* [HWR] DEBUG 2016-05-18 16:00:42,209 [MOTOR CALLBACK]
* [HWR] DEBUG 2016-05-18 16:00:42,209 [MOTOR CALLBACK]   {'CentredPositions': {1: {'motorPositions': {'sampx': 1.3152913222671776, 'sampy': 1.7537217630229036, 'phi': 2.630582644534355, 'focus': -0.42, 'beam_x': 0.1, 'beam_y': 0.1, 'kappa': 0.0009, 'zoom': 2.1921522037786296, ' kappa_phi': 311.0, 'phiz': 0.8768608815114518, 'phiy': 0.4384304407557259}, 'name': 'pos1', 'posId': 1, 'selected': True, 'y': 346.8421052631579, 'x': 362.8078529657477, 'type': 'TMP'}}, 'Signal': 'minidiffStateChanged', 'Motors': {'Sampx': {'Status': 2, 'position': 0}, 'Sampy': {'Status': 2, 'position': 0}, 'Phi': {'Status': 2, 'position': 0}, 'BackLightSwitch': {'Status': 0, 'position': 0}, 'Zoom': {'Status': 'unknown', 'position': 2}, 'Focus': {'Status': 2, 'position': 0}, 'FrontLight': {'Status': 2, 'position': 0}, 'BackLight': {'Status': 2, 'position': 0}, 'PhiZ': {'Status': 2, 'position': 0}, 'PhiY': {'Status': 2, 'position': 0}, 'FrontLightSwitch': {'Status': 0, 'position': 0}}, 'Message': 'minidiffStateChanged', 'Data': True}
```

**Comment by meguiraun** [comment]
arrghhh, of course it will not work very well... I will check some small changes on the server and push to this wip-pr

**Comment by marcus-oscarsson** [comment]
Hola !

No problem, we get the idea and it looks really great, the important thing is that it works 
for you guys :) I don't want to take your time with smaller issues like this, focus on whats important for you. I guess your quite busy right now. We will sort out these things eventually :)

Good evening !

**Comment by meguiraun** [comment]
hej,
Added some dirty fixes... so you can run, add a sample, get a centring point... With dirty I mean that I hardcoded a few things:

* Set in manual mode from the beginning: can be added as a parameter at server launch (this was preventing the addition of a sample)
* Force the queue to unpause, I do not why is paused by default...
* Uncomment the fake execution lines in the routes.Queue -> executeEntryWithId
* The dummy diff 3-click-centring only needs a single click (cof cof), but the client expects 3... You can save the point anyway.

I dare to add these fixes because this is a WIP pr, so you can test, I will remove/fix later in a proper way.

Tack för feedbacken!

**Comment by marcus-oscarsson** [comment]
Hej !,

Okey great thanks for the fast response, I gave it a try and it works now :) :+1: . I noticed some strange behavior when centering, it essentially works, we can get back to that at some other time, I guess you might know about it.

Regarding centered positions, we might need to give the user some warning when deleting a position already assigned to a task, did you already consider this ?

Cheers,
Marcus

**Pull request closed without merging**
