### PR TITLE
Merging top into left menu

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hi again

So here is finally the PR for the menu, you can consider it a design proposal if you for some reason don't think its a good idea to merge it right away.

Marcus

### CODE REVIEW

**Comment by amilan** [comment]
Hi, 
As I have commented in the issue #242, tomorrow we will have a review of the samplegrid prototype and we will also review this one, so again, feedback is coming ...
Regards,
Antonio.

**Comment by marcus-oscarsson** [comment]
Hello,

This can maybe me merged now, regardless on what we show in the top menu ?

Marcus

**Comment by mguijarr** [comment]
:+1:

**Comment by amilan** [comment]
Hi, Ok, looks like now it's kind of agreed :)

**Pull request merged**
