### PR TITLE
Unittesting server

### PR DESCRIPTION
**Pull request by meguiraun**
hoooooray!!!

A very minimal set of tests: add/get/delete sample, hardcoded sample data dict, and those three tests are related to each other and act on the same queue... at least is something!

Be careful: check the path modification in the `__init__.py`, I do not know if the change affects you ... if so I can find alternatives

### CODE REVIEW

**Comment by amilan** [comment]
Yuhuuuuuuuuu! It's a beginning! 👍 
I will have a look later on.
Thanks!

**Comment by mguijarr** [comment]
It's a pleasure to see unit tests make you so enthusiastic guys ;)

**Comment by meguiraun** [comment]
enthusiastic, enthusiastic...

**Comment by mguijarr** [comment]
@meguiraun : if we are going to be serious about unit tests, maybe we should consider using [pytest](http://doc.pytest.org/en/latest/). It's a good start :) Now we need to write more test cases...

**Comment by meguiraun** [comment]
thanks, gonna have a look at that

**Pull request merged**
