### PR TITLE
SampleMotors  + Refactored logging to redux/react

### PR DESCRIPTION
**Pull request by bolmsten**
A new GUI for moving samples and I have refactored the logging to a react-redux version. 

With the new linting rules I get a lot of errors that I will try to fix In the coming days for my code.

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Hi @bolmsten,

Sorry for the linting errors, the new rules are just a proposal so please let us know what you think, if you like some changes or if you think they are to strict ?. We can discuss these things in issue #165.

I'm taking a look at your PR right now and I hope I get the time to merge this morning.

Marcus

**Comment by marcus-oscarsson** [comment]
@blomsten,

Well done, the UI is starting to take shape now, its great to see :).

My idea with the PopInput was that it should be general enough to be used with most beamline "attributes" for example motors or something like energy. The benefit with the PopInput is that it also have the concept of state with corresponding graphical representation (i.e background color). The state (IDLE, MOVING, ON-LIMIT) is something that is very important for motors. Its also important to be able to abort a movement/action.

Did you consider using it or did you find limitations with it that made it impossible to use ?. In anyways I would suggest to generalize it so what we can use it for most of the beamline "attributes". What do you think ?

Something I thought about regarding the logging feature is that each entry is, as far as I understand, now stored in the data model of redux. I suspect that Matias had this in mind when he wrote it and that there might be a reason for that he did not use redux. I imagine that the number of log entries we will have for a session might be quite large,  and so will the size of the redux data model. Do you think that will be an issue, perhaps I'm overthinking it a bit ?

Cheers,
Marcus

**Comment by bolmsten** [comment]
@marcus-oscarsson 

I tried initially to use the Popinput and I like the idea of having a general component for this. 

The problem I faced with your Popinput was that the functionality that you need and the functionality that I need was very different. The fields I have should be input fields with stepping functions onClick for immediate updating and In the future you should be capable of setting the step sizes (hardcoded at the moment). 

I could generalize the Popinput to get it's HTML from props.children but what I noticed then was that I ruined the purpose of the Popinput. I should probably have created a own version of Popinput component for my use case.

Regarding the logging, it will not be more work for the browser to use the Redux Framework compared to ordinary Javascript I think,  so far I have not noticed any problems.

**Comment by marcus-oscarsson** [comment]
@bolmsten,

I see,  My intention is that it should also be possible to specify a custom control for the input, as a child or as a property. Just like its possible to specify a custom loading control. We could even Imagine the possibility to specify one control per state, even if I don't think that's immediately useful.

I'll update the PopInput to make it possible to specify the custom input control and then we can try to integrate that into the sample position control UI. I don't really see anything that directly prevents us from doing that, but I might be mistaken. What do you think ?.

Regarding the logging, it was just a concern for the size of the data model on the client that I was thinking about. Its perhaps as you say not a problem.

**Comment by bolmsten** [comment]
@marcus-oscarsson 

I think it should be possible to do and If you want to try please do. Do you want to accept this PR now and then do a refactoring for it or should I wait for the updated PopInput?

Regarding the logging I think we can try this new version and if we get into trouble I will refactor it. The size of the data model would be the same for the browser I guess, in my case it is saved in the redux state and in the old it is saved on the window object.

**Comment by marcus-oscarsson** [comment]
@bolmsten 

Sorry for the delay, Ive started to do the necessary changes to the PopInput It should be done by tomorrow. I'll leave the decision about the merging to Matias, its all fine by me :). I have notified Matias about the PR and he will a take a look as soon as he can (hes working on the beamlines today).

Good evening,
Marcus

**Comment by mguijarr** [comment]
Hello :)

I propose to wait for the updated PopInput, then if you don't mind you can change the code to use
it, and then I would happily merge the PR.
Then we can make another PR afterwards for adding state information for motors (eg. using
background color with some color code for READY, MOVING, etc.).

Would it be ok like this ?

About the logging: I didn't want to *reduxify* it on purpose, because I didn't want the global redux
state to hold all log records (which can be a lot !), because I thought we may want to serialize
the redux state entirely to be able to restore it when needed (for example, if user closes the
web browsers, restarts it and logs in again).

I have to admit I don't know how redux internals work, if the different reducers states are separated
it's probably ok ? It's just that in doubt I preferred to keep log records away from the redux state.

By the way I like how you simplified the "log navigation", it's better to have only 1 label with page
number instead of many boxes :+1:

**Comment by marcus-oscarsson** [comment]
@bolmsten, @mguijarr 

So Ive created a PR with the new more generic PopInput please see PR #168. I hope you find it useful :)

I agree with Matias the new log navigation is nice !

Cheers !

**Comment by marcus-oscarsson** [comment]
Me and Fredrik did some work together and we merged this PR with  #168 (Attempt to create a more generalized version of the PopInput). So I'm closing this PR.

**Pull request closed without merging**
