### PR TITLE
Continuing LIMS and queue integration

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Dear all,

I wanted to divide this PR into two PRs, one for queue integration and one for LIMS but I finally decided that it was easier to just have one. In anyways, that's why there are both LIMS and queue related features in the same PR :). Ill try to avoid this in the future ...

I started to take care of the sample order, since the JS object is non ordered. Ive created a structure called sampleOrder and refactored the grid-ordering slightly for that purpose. The next thing to do is to use this in the queue and finally of course on the back end so that the samples are executed in order :). Exactly how to use this have to be determined it could perhaps be replaced by or replace the existing todo structure.

The "execution state" of a task was moved from dislpayData to queue. There are also some smaller improvements to the grid, like disabling certain controls while executing.

For the lims part, Ive started to prepare for having the data collection results being shown (LIMS collection ID being sent as part of the result) . The prefix is now taken from the Session object. There is also a new UI for filtering (although not completely done yet).

The mockup objects for lims are also used by default :)

Ive not yet had the time to take care of the proposal list for the "one login" to "many proposal" mapping. Ill try to do it next week (when our shutdown is over).

Cheers,
Marcus

### CODE REVIEW

**Comment by bolmsten** [comment]
Thank you!

**Comment by mguijarr** [comment]
This solves #346 it seems ?

Is there really a need for this: proposal list for the "one login" to "many proposal" mapping ? It's for you guys at MAX IV, as far as I know you are using user login, then proposal for ISPyB ?

**Comment by bolmsten** [comment]
Yes it does!

We will need something like that but it does not have priority at the moment.

**Comment by mguijarr** [comment]
Ok. So I add an issue for this, I let you give the priority you want and assign someone on your side or we will do it later.

**Pull request merged**
