### PR TITLE
Remove unused deps

### LINKED ISSUE #1242: Some unused and some missing Javascript dependencies?
Seems like we might have a bunch of unused Javascript dependencies and some that are missing (!?), see below. Maybe we could investigate further and tidy up.

```none
$ pnpx depcheck
Packages: +126
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 126, reused 76, downloaded 50, added 126, done
Unused dependencies
* @fortawesome/react-fontawesome
* dustjs-helpers
* dustjs-linkedin
* everpolate
* history
* jsmpeg
* liform-react
* plotly.js
* popper.js
* react-clipboard.js
* react-plotly.js
* react-router
* react-sticky
* shortid
* underscore
* ws
Unused devDependencies
* @testing-library/react
* @testing-library/user-event
* babel-preset-react-app
* concurrently
* less
* less-watch-compiler
* sass
* wait-on
* webpack
* webpack-dev-server
Missing dependencies
* @babel/eslint-parser: ./.eslintrc.js
* eslint-plugin-unicorn: ./.eslintrc.js
* eslint-plugin-promise: ./.eslintrc.js
* eslint-plugin-sonarjs: ./.eslintrc.js
* eslint-plugin-simple-import-sort: ./.eslintrc.js
* eslint-plugin-react-hooks: ./.eslintrc.js
* eslint-plugin-jest-dom: ./.eslintrc.js
* eslint-plugin-testing-library: ./.eslintrc.js
* eslint-plugin-jest-formatting: ./.eslintrc.js
```

### PR DESCRIPTION
**Pull request by axelboc**
Fix #1242

All in all, `depcheck` did a good job :blush: — I did go over all the deps myself just in case it missed one (it didn't). Do please double check thoroughly.

### Unused dependencies

* `dustjs-helpers`: used but imported with `require`; kept :green_circle: 
* `dustjs-linkedin`: used but imported with `require`; kept :green_circle: 
* `everpolate`: unused; removed :wastebasket: 
* `history`: unused; removed :wastebasket: 
* `jsmpeg`: used via `ui/src/components/SampleView/jsmpeg.min.js`, not via NPM package, which is obsolete compared to `jsmpeg.min.js`; removed :wastebasket: 
* `liform-react`: unused; removed :wastebasket: 
* `plotly.js`: peer of react-plotly.js; unused; removed :wastebasket: 
* `popper.js`: unused; removed :wastebasket: 
* `react-clipboard.js`: unused; removed :wastebasket: 
* `react-plotly.js`: unused; removed :wastebasket: 
* `react-router`: peer of react-router-dom; used; kept :green_circle: 
* `react-sticky`: unused; removed :wastebasket: 
* `shortid`: unused; removed :wastebasket: 
* `underscore`: unused; removed :wastebasket: 
* `ws`: unused; removed :wastebasket: 

### Unused devDependencies

* `@testing-library/react`: unused but should be :joy: ; kept for now :green_circle: 
* `@testing-library/user-event`: unused but should be :joy: ; kept for now :green_circle: 
* `babel-preset-react-app`: direct dep of `create-react-app`; no need to install ourselves; ~removed~ EDIT: re-added in #1274  :green_circle: 
* `concurrently`: unused; removed :wastebasket: 
* `less`: only one `.less` file `ui/src/components/PeriodicTable/style.less` with only a few mixins for CSS browser prefixing; styles should be written in pure CSS; browser prefixing is done automatically by `autoprefixer` based on `browserslists` config; removed :wastebasket: 
* `less-watch-compiler`: removed :wastebasket: 
* `sass`: no SASS/SCSS files found; removed :wastebasket: 
* `wait-on`: used in CI to wait for server to start before testing with Cypress; kept :green_circle: 
* `webpack`: dependency of `webpack-dev-server`; safer to keep in case specified version range matters :green_circle: 
* `webpack-dev-server`: dependency of `react-scripts`; safer to keep in case specified version range matters :green_circle: 

### Missing dependencies

All of these are direct dependencies of `eslint-config-galex`, so no need to install them. :green_circle:

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
Nice job with the investigation! I will try to give it a check from our side, but there is not much doubt you know this stuff better than we do. : )

**Comment by fabcor-maxiv** [comment]
Could we get a pre-commit hook or maybe a GitHub Action to make sure it stays clean? Would that make sense?

**Comment by marcus-oscarsson** [comment]
Nice, well done and big thanks !

**Comment by axelboc** [comment]
> Could we get a pre-commit hook or maybe a GitHub Action to make sure it stays clean? Would that make sense?

Hmm, I feel like it would be a bit brittle and not really worth the effort. An unused dependency just adds a few ms to the installation time; nothing worth worrying about too much in my opinion, especially since it doesn't take long to do a bit of a clean-up like this from time to time.

**Review by fabcor-maxiv — APPROVED** [review]
I did some sanity check (including build JS UI from scratch), and did not encounter any issue.

**Pull request merged**
