### PR TITLE
MXCUBEApplication and Server static classes 

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Discovered that MXCUBEApplication and Server got instanciated at some point causing an issue of
shadowing attributes.

 - MXCUBEApplication and Server are static classes and does not need to ( should not be) instanceanciated
 - Simplified the code removed the globlas mxcube and server (not needed)

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
Can we enforce this somehow? I do not recall how this is typically handled in Python. Maybe with an `__init__` that raises `NotImplemented`?

**Comment by marcus-oscarsson** [comment]
Yes it can be done, its a good idea :)

**Comment by marcus-oscarsson** [comment]
Like so :)

**Comment by fabcor-maxiv** [comment]
For consistency: in `mxcube3/__init__.py`, why not `import ... as server` and `import ... as mxcube`? Or the other way around (which might be better actually, not sure) use `Server` and `MXCUBEApplication` consistently everywhere?

**Comment by marcus-oscarsson** [comment]
Yes, that makes sense :)

**Pull request merged**
