### PR TITLE
Downgrade to `python-ldap==3.4.3` in `poetry.lock`

### PR DESCRIPTION
**Pull request by fabcor-maxiv**
Downgrade `python-ldap` from version `3.4.4` to `3.4.3` in `poetry.lock` because we want `poetry.lock` and `conda-environment.yml` pins in sync and there is no version `3.4.4` in the *conda* repositories.

<https://github.com/mxcube/mxcubeweb/pull/1515>
<https://github.com/conda-forge/python-ldap-feedstock/pull/27>

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
This aims to replace <https://github.com/mxcube/mxcubeweb/pull/1515>.

And is (loosely) related to <https://github.com/mxcube/mxcubeweb/issues/1510>.

**Comment by marcus-oscarsson** [comment]
@fabcor-maxiv Could you please rebase the branch ?

**Comment by fabcor-maxiv** [comment]
Rebase done. Waiting for the ReadTheDocs build to finish successfully. I do not know yet if the issue is on ReadTheDocs side and we only need to wait and re-trigger the build at a later point, or if the issue is on our side. Locally I can build the documentation just fine. I can not think of any recent change in the git repository that would cause issues with docs build.

**Comment by marcus-oscarsson** [comment]
@fabcor-maxiv, I noticed this too. No, the docs seem to build properly as you mention above. The error is the following:
```
 mamba run --name mxcubeweb python -m sphinx -T -E -b html -d _build/doctrees -c docs docs/source ${READTHEDOCS_OUTPUT}/html
Command killed due to timeout or excessive memory consumption 
```
I'd say that its more on the read the docs side.

**Comment by marcus-oscarsson** [comment]
Its perhaps some dependency change that somehow induces this. I'm not sure at the moment. As you also mentioned nothing changed that would directly effect this. Its of course great if we can solve the issue with the docs build. In the mean time feel free to merge this PR, as its not changing any documentation.

**Pull request merged**
