### PR TITLE
remove "get samples from SC" button

### PR DESCRIPTION
**Pull request by meguiraun**
Dealing with issue https://github.com/mxcube/mxcubeweb/issues/1437

from 
Screenshot 2024-10-04 at 11 01 34

to:
Screenshot 2024-10-04 at 12 39 28

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Seems reasonable to me. I think I would prefer the `Get samples` button before the `Create new sample` button. It somehow feels like `Get samples` will be the one that is used more often ?

**Comment by meguiraun** [comment]
> Seems reasonable to me. I think I would prefer the `Get samples` button before the `Create new sample` button. It somehow feels like `Get samples` will be the one that is used more often ?

sure, makes sense for ux point of view

**Comment by marcus-oscarsson** [comment]
Looks good, to me. You can rebase and merge :)

**Comment by jbflo** [comment]
What about having the get samples trigger automatically .on login for example ? I remember this was asked before .

**Pull request merged**
