### PR TITLE
Remote access slave read only

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hi,

Remove access slave read only and small badge on-top of RA icon indicating number of observers

Marcus

### CODE REVIEW

**Comment by meguiraun** [comment]
I have an issue, when the second guy logins the grayed out overlay is above the 'Observer Mode', so I cannot type my name or click ok

**Comment by marcus-oscarsson** [comment]
Oh, yes i forgot to fix that, ill upload a fix for that ASAP

**Comment by meguiraun** [comment]
thanks for the fix. Small issues still:
* When asking for control, there is a blank cover from rigth under the 'Ask for control' until the end of the page
* When giving control the second users receives the 'obersever mode' dialog, and then the 'You were given control'
* From that point onwards, none of the users can operate the gui

**Comment by marcus-oscarsson** [comment]
Hey,

Im aware of those issues although they are separate from this PR, this PR is only for the read only div and the number badge not for the entire RA feature.

The take and give control feature have been broken by previous PRs and needs to be fixed, thats what I intend to do next. The blank cover is also something else, which we need to take a look at.

**Comment by meguiraun** [comment]
yes sure, I do not intend to fix the whole remote operation, I know it required more work. But with this PR is in a worse situation. We cannot apply the read only div to both master and slave at the same time

**Comment by marcus-oscarsson** [comment]
That's, strange were are normally not doing that, it works fine here, given that the give take control is a bit broken/glitchy but giving control usually works one time.

I can imagine that there is a bug in the give take control feature that prevents us from correctly passing from salve to master, so that we sometimes have no master. Effectively the read only div stays. So I already started to take a look at it and there will be a PR for that as well.

**Comment by marcus-oscarsson** [comment]
So I took the opportunity to add a couple of fixes to the give/take control mechanism its really not a part of this PR but I imagine it makes things easier for you to test.

**Comment by meguiraun** [comment]
thanks

**Pull request merged**
