### PR TITLE
Reinstated lost fixes - Needed for GPhL workflow to run. See issue #895

### PR DESCRIPTION
**Pull request by rhfogh**
It looks like these fixes got lost in the merging of PRs. One is needed for Issue #895

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Hi @rhfogh, I'm waiting with this for a little bit longer. There is a pending fix for this issue in [PR 660](https://github.com/mxcube/mxcubecore/pull/660). I will have a closer look when I get back after Christmas.

**Comment by rhfogh** [comment]
Could we leave this hanging for a bit longer, just as a reminder? Hopefully this will have  been made unnecessary by PR #900, but it might be a while before I can test that. Once I test it, I shall remove (or, unlikely, reporopose) it.

**Comment by marcus-oscarsson** [comment]
Sure sounds good :), no harm in that

**Comment by rhfogh** [comment]
No longer necessary - problem fixed elsewhere

**Pull request closed without merging**
