### PR TITLE
Fix size of step inputs in Chrome

### LINKED ISSUE #1433: Motor value does not show in ui
After the latest changes the UI does not show the current values of some motors. Only the step input is visible.
Screenshot from 2024-10-02 15-14-36Screenshot from 2024-10-02 15-14-54

One exception are the motor fields hidden behind the setting button of sample alignment
Screenshot from 2024-10-02 15-15-09

### PR DESCRIPTION
**Pull request by axelboc**
Fix #1433 

@walesch-yan can you please double check? I'm remote and can't run MXCuBE-Web on my Windows machine. Otherwise, I can investigate tomorrow.

### CODE REVIEW

**Comment by walesch-yan** [comment]
This did not solve it

**Comment by axelboc** [comment]
Ok, strange. I'll look at it tomorrow, then. The styles of the `MotorInput` need a deeper clean-up, I think.

**Comment by axelboc** [comment]
Turns out Chrome just ignores the `size` attribute on the `input`...

image

**Comment by fabcor-maxiv** [comment]
But what kind of `<input>` is that? Not all of them have the `size` attribute. Or am I misunderstanding things?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#size

**Comment by axelboc** [comment]
Wow you're right, it's [not valid for `number` inputs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#controlling_input_size). Why it isn't, I don't understand. Anyways, well spotted! :fishing_pole_and_fish: 

I've removed the `size` attribute and used an `em` width in the CSS. I've done the same in `BeamlineAttributeForm`.

**Pull request merged**
