### PR TITLE
#402 Remote access

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hey !

So here is the basic feature for giving and requesting control. The exact sequence of dialogs and the contents of each dialog can perhaps be refined and any suggestions are welcome.

Each observer is prompted for a name which is the name they want to communicate to the master (the same name can perhaps later be used for the chat). The name is for the moment not linked to the proposal or username, but is just a name the user would like to be associated with.

An observer can ask for control and supply a optional message that is displayed to user in control. The user in control can then decide if she wants to keep the control or pass it to the observer.

Requesting control is done by clicking on the remote access icon on the bottom left.

Marcus

### CODE REVIEW

**Comment by meguiraun** [comment]
sorry for the delay @marcus-oscarsson and @mguijarr, we will have a look at the PRs today.

**Comment by bolmsten** [comment]
I am having problems running this. Is everything working for you @marcus-oscarsson ?

**Comment by marcus-oscarsson** [comment]
Hey !

Yes its working fine here (otherwise I would not give it to you), whats the problem you have ?

Marcus

**Comment by marcus-oscarsson** [comment]
@meguiraun No problem take your time

**Comment by bolmsten** [comment]
Uncaught Error: Cannot find module "../components/RemoteAccess/Observer"(…)
main.js:696 [WDS] Hot Module Replacement enabled.
main.js:719 [WDS] Errors while compiling.
main.js:721 ./mxcube3/ui/components/RemoteAccess/Observer.jsx

/Users/frebol/Desktop/mxcube3/mxcube3/ui/components/RemoteAccess/Observer.jsx
  86:1  error  Parsing error: Only one default export allowed per module

✖ 1 problem (1 error, 0 warnings)
errors @ main.js:721
main.js:721 ./mxcube3/ui/components/RemoteAccess/Observer.jsx
Module build failed: SyntaxError: Only one default export allowed per module. (86:0)

  84 | }
  85 | 
> 86 | export default connect(
     | ^
  87 |   mapStateToProps,
  88 |   mapDispatchToProps,
  89 | )(Master);

BabelLoaderError: SyntaxError: Only one default export allowed per module. (86:0)

  84 | }
  85 | 
> 86 | export default connect(
     | ^
  87 |   mapStateToProps,
  88 |   mapDispatchToProps,
  89 | )(Master);

    at transpile (/Users/frebol/Desktop/mxcube3/node_modules/babel-loader/index.js:52:13)
    at Object.module.exports (/Users/frebol/Desktop/mxcube3/node_modules/babel-loader/index.js:131:12)
 @ ./mxcube3/ui/containers/RemoteAccessContainer.jsx 18:16-62errors @ main.js:721
main.js:721 ./mxcube3/ui/components/RemoteAccess/Master.jsx

/Users/frebol/Desktop/mxcube3/mxcube3/ui/components/RemoteAccess/Master.jsx
  39:1  error  Parsing error: Only one default export allowed per module

✖ 1 problem (1 error, 0 warnings)
errors @ main.js:721
main.js:721 ./mxcube3/ui/components/RemoteAccess/Master.jsx
Module build failed: SyntaxError: Only one default export allowed per module. (39:0)

  37 | }
  38 | 
> 39 | export default connect(
     | ^
  40 |   mapStateToProps
  41 | )(Observer);
  42 | 

BabelLoaderError: SyntaxError: Only one default export allowed per module. (39:0)

  37 | }
  38 | 
> 39 | export default connect(
     | ^
  40 |   mapStateToProps
  41 | )(Observer);
  42 | 

    at transpile (/Users/frebol/Desktop/mxcube3/node_modules/babel-loader/index.js:52:13)
    at Object.module.exports (/Users/frebol/Desktop/mxcube3/node_modules/babel-loader/index.js:131:12)
 @ ./mxcube3/ui/containers/RemoteAccessContainer.jsx 22:14-58

**Comment by bolmsten** [comment]
So it seems to be some problem with having multiple exports per module that makes babel crash and then it cant find some component

**Comment by marcus-oscarsson** [comment]
I see,

That's strange, it works fine here and I don't get this message Ill take a look and see what I can find.
To me its the first line that tells me something: 

    Uncaught Error: Cannot find module "../components/RemoteAccess/Observer"(…)

Well ill take a look and see what I can find.

Marcus

**Comment by marcus-oscarsson** [comment]
Hey,

I noticed that I by mistake had interchanged the name of Master and Observer components, which should not really have any effect in the end. In anyways it was something to fix, it perhaps helps ?

Marcus

**Comment by bolmsten** [comment]
The problem you have is that in the files master and observer you do "export default" twice, this does not work. Export default is built for being used only once, maybe you have a forgiving babel version or something but mine does not compile. When I removed the export default for the class everything seemed fine

**Comment by bolmsten** [comment]
Some initial feedback:

I see this warning:

main.js:11499 Warning: Failed propType: Required prop `onHide` was not specified in `Modal`. Check the render method of `ObserverDialog`.

Also it seems to break if I deny access to a user that is asking. Then I still got you have become a observer

**Comment by marcus-oscarsson** [comment]
You should get something that says:

   " You were denied control "

Ive tried a bit and I cant reproduce what you got with you have become an observer that seems a bit
strange. Are you running from the same host ? Its IP based so it wont work if you are running the observer on the same computer.

Marcus

**Comment by marcus-oscarsson** [comment]
Sorry for the export, should be fixed now. I use the version of babel that we have in our packages.json which seems a bit old (6.5.2). I guess that's why i don't see anything here. We should maybe update the packages.json

**Comment by marcus-oscarsson** [comment]
Actually sorry, there is a bunch of babel packages but not the one called just babel. I'm using 6.4.0 of babel-core if its of any interest. It would be good to know if you have updated babel or not, Im using the versions in our pacakges.json.

**Pull request merged**
