### PR TITLE
Photon Flux,  InOutMediator fixes

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hi,

- Added photon flux reading, the display was added to the machine info for the moment, this might change at a later stage.

- Various smaller improvements to the InOutMediator (more general)

- Taking proposal information from the redis session so that its not lost in case of server restart

- Smaller fixes to the video streaming, (making sure that the video has even size)

Cheers !
Marcus

### CODE REVIEW

**Comment by meguiraun** [comment]
hej @marcus-oscarsson, thanks for this. Some small issues while doing a quick test (fresh clone from your branch, update to latest 2.2)

* I had to install react 15.6.1 to avoid unmet dep error (I know this is out of this pr)
* For the`DuoStateHOMediator `: fast_shutter, safety_shutter and beamstop fail:
```
017-06-19 07:10:32,941 |HWR    |ERROR  | Failed to get fast_shutter info
Traceback (most recent call last):
  File "/mxcube/mxcube3/mxcube3/ho_mediators/beamline_setup.py", line 119, in dict_repr
    attributes.update({"fast_shutter": fast_shutter.dict_repr()})
  File "/mxcube/mxcube3/mxcube3/ho_mediators/beamline_setup.py", line 491, in dict_repr
    "value": self.get(),
  File "/mxcube/mxcube3/mxcube3/ho_mediators/beamline_setup.py", line 472, in get
    return INOUT_STATE.STR_TO_VALUE.get(self._get_state(), 2)
  File "/mxcube/mxcube3/mxcube3/ho_mediators/beamline_setup.py", line 434, in _get_state
    state = self.STATES.TO_INOUT_STATE.get(state, INOUT_STATE.UNDEFINED)
  File "/mxcube/mxcube3/mxcube3/ho_mediators/beamline_setup.py", line 177, in __getattr__
    return getattr(self._ho, attr)
  File "/mxcube/mxcube3/mxcube3/HardwareRepository/BaseHardwareObjects.py", line 330, in __getattr__
    raise AttributeError(attr)
AttributeError: STATES
```
* Photon flux: the popup displays the same text as the machine info (e.g. current, fillmode)
```
2017-06-19 07:10:32,959 |HWR    |ERROR  | Failed to get photon flux
Traceback (most recent call last):
  File "/mxcube/mxcube3/mxcube3/ho_mediators/beamline_setup.py", line 148, in dict_repr
    flux = self.getObjectByRole("flux")
  File "/mxcube/mxcube3/mxcube3/ho_mediators/beamline_setup.py", line 84, in getObjectByRole
    return self._ho_dict.setdefault(name, PhotonFluxHOMediator(ho, "flux"))
  File "/mxcube/mxcube3/mxcube3/ho_mediators/beamline_setup.py", line 715, in __init__
    ho.connect("valueChanged", self.value_change)
AttributeError: 'NoneType' object has no attribute 'connect'
```

**Comment by marcus-oscarsson** [comment]
Hi 

Sorry, yes it was some missing code for the mockups. I only tested on the beamline so I forgot to add some mockup code. Ive made a PR for hardware objects that improve the ShutterMockup, which is necessary to run this PR properly.

Marcus

**Comment by meguiraun** [comment]
once you update the submodule I accept this pr. I tested and it is fine.

**Comment by meguiraun** [comment]
mmm... still conflicts?

**Comment by marcus-oscarsson** [comment]
How about now ?

**Comment by meguiraun** [comment]
thanks!

**Pull request merged**
