### PR TITLE
[react-contexify]  update to 6.0.0

### LINKED ISSUE #1426: Seems like [react-contexify] Context Menu stopped working
[react-contexify] Context Menu stopped working on components/Equipment/Harvester.jsx && components/Equipment/PlateManipulator.jsx . 

Maybe in there also components/SampleQueue/CurrentTree.jsx

@marcus-oscarsson  can you check if this the case for the render of  components/SSXChip/SSXChip.jsx

it's like the Context are are not showing at all, or show from a unknown position.  

*** Edited add error Message from the library  ***
image

### PR DESCRIPTION
**Pull request by jbflo**
This fix [Issue](https://github.com/mxcube/mxcubeweb/issues/1426)

### CODE REVIEW

**Comment by axelboc** [comment]
There are a bunch of changes in v6, including breaking changes (CSS import path, CSS classes, etc.), might be worth doubling checking those. There may also be opportunities to improve/simplify the code with some of the new features, maybe? :shrug:  https://github.com/fkhadra/react-contexify/releases/tag/v6.0.0

**Comment by marcus-oscarsson** [comment]
@axelboc, yes that would probably be worth doing. What do you think @jbflo ? Ill merge this for now though as it seems to fix the issue, and then we can follow up with some improvements.

**Comment by marcus-oscarsson** [comment]
@jbflo, @axelboc, is it perhaps worth double checking the impact of the backward incompatible changes before merging ?

**Comment by jbflo** [comment]
Yes. We can even remove the use of this library since we had some issues with the positioning in the pass for menu with very big Height.


We have a Generic ContexMenu Component  already we can make the necessary modifications to make it work everywhere.

**Comment by marcus-oscarsson** [comment]
@jbflo, yes I remember that we already discussed. Sounds like a good idea then

**Comment by jbflo** [comment]
> @jbflo, yes I remember that we already discussed. Sounds like a good idea then

I had a look at the Release notes [I should had check before sorry]
I made the change for the css  Breaking changes.  but it's weird that it was still working with the old css path. 

You can Merge this as it is. 
Or 
we can close this one and go on  [all in one] improve/simplify the code on another PR.  
both fine by me.

**Comment by axelboc** [comment]
It's worth merging I think, in case the refactor/migration to the other solution takes longer than expected.

**Comment by marcus-oscarsson** [comment]
Thanks guys !

**Pull request merged**
