### PR TITLE
Notify requester when denying request for control

### LINKED ISSUE #1280: Denying request for control does not notify requester
The _Asking for control_ modal doesn't close itself and the requester doesn't know he's been denied control.

Peek 2024-07-02 16-42

### PR DESCRIPTION
**Pull request by axelboc**
Draft until #1346 is merged.

Fix #1280. I also put a bit of colour on the buttons to approve/deny the request.

Peek 2024-08-16 16-17

### CODE REVIEW

**Comment by fabcor-maxiv** [comment]
Unrelated: I see the message from the one asking for control is not displayed to the one in control.

**Comment by marcus-oscarsson** [comment]
Very nice thanks !

**Comment by axelboc** [comment]
No worries. FYI, I'm still working on some more fixes/refactoring of this "request for control" feature, including the one that @fabcor-maxiv reported.

**Comment by axelboc** [comment]
Not satisfied with this solution; it's too imperative.

I would like to take advantage of the `observerChanged` WS message instead, and I'd like to move all the side effects out of the `observerChanged` handler. The flow should instead be:

1. Server state changes
2. Server notifies all clients with WS `observersChanged` message
3. Clients request fresh server state and update their local states (i.e. `login.user` and `remoteAccess.observers`)
4. UI reacts to local state updates (including showing/hiding dialogs)

**Comment by marcus-oscarsson** [comment]
Ok

**Comment by marcus-oscarsson** [comment]
Well done (good decision)

**Pull request closed without merging**
