### PR TITLE
Improved configuration handling 

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Improved configuration handling 

 - Using pydantic models to define configuration data
 - Moved all models to models module
 - Split ui and app config

### CODE REVIEW

**Review by meguiraun — APPROVED** [review]
looks good to me, I am a _bit_ behind so not much to say (I did run on my machine tough)

**Review by rhfogh — APPROVED** [review]
I am not really in a position to evaluate (or actually test) this, but it looks very good.

**Comment by meguiraun** [comment]
if you fix the conflicts, I merge it :)

**Comment by marcus-oscarsson** [comment]
Ok, done

**Pull request merged**
