### PR TITLE
Upgrade to Webpack 2 + all dependencies update, including react-bootstrap and redux-form

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hi,

Me and Matias have been working on some library updates the biggest changes are upgrade to webpack 2.2.1 and webpack dev server 2.4.1. We have also cleaned up the configuration files and package.json

We have not yet tested the production version, but the dev version seems to work fine.

Marcus

### CODE REVIEW

**Comment by mguijarr** [comment]
98% done ;) See you on Monday.

**Comment by mguijarr** [comment]
Finally it took a bit more time to finish this one :)

It's done !

Happy upgrading.

**Comment by meguiraun** [comment]
I will try to have a look at this... but it is huuuuge!! ;)
Thanks for the effort

**Comment by meguiraun** [comment]
trying to run from a clean install (`rm -rf node_modules; npm install; npm run`)

Which npm version are you using?
I get the following with npm v2.15.9 on linux (v3.10.10.on mac looks ok)
```
@ ./mxcube3/ui/main.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8090 main.jsx

ERROR in ./mxcube3/ui/img/loader.gif
Module build failed: Error: /mxcube/mxcube3/node_modules/gifsicle/vendor/gifsicle: /mxcube/mxcube3/node_modules/gifsicle/vendor/gifsicle: cannot execute binary file

    at Socket.<anonymous> (/mxcube/mxcube3/node_modules/imagemin-gifsicle/index.js:39:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:536:20)
 @ ./mxcube3/ui/containers/SampleQueueContainer.js 62:14-42
 @ ./mxcube3/ui/containers/SampleViewContainer.js
 @ ./mxcube3/ui/main.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8090 main.jsx

ERROR in ./mxcube3/ui/img/mxcube_logo20.png
Module build failed: Error: Command failed: /mxcube/mxcube3/node_modules/optipng-bin/vendor/optipng -strip all -clobber -force -fix -out /mxcube/mxcube3/b8569754-31c8-47e5-92cd-5b9a2e655a32 /mxcube/mxcube3/74f8249e-4d33-4a05-851a-53fc4014832f
/mxcube/mxcube3/node_modules/optipng-bin/vendor/optipng: /mxcube/mxcube3/node_modules/optipng-bin/vendor/optipng: cannot execute binary file

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)
 @ ./mxcube3/ui/components/Login/Login.jsx 26:19-57
 @ ./mxcube3/ui/containers/LoginContainer.js
 @ ./mxcube3/ui/main.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8090 main.jsx

ERROR in ./mxcube3/ui/img/busy-indicator.gif
Module build failed: Error: /mxcube/mxcube3/node_modules/gifsicle/vendor/gifsicle: /mxcube/mxcube3/node_modules/gifsicle/vendor/gifsicle: cannot execute binary file

    at Socket.<anonymous> (/mxcube/mxcube3/node_modules/imagemin-gifsicle/index.js:39:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:536:20)
 @ ./~/css-loader?{"modules":false}!./mxcube3/ui/components/PopInput/style.css 6:330-369
 @ ./mxcube3/ui/components/PopInput/style.css
 @ ./mxcube3/ui/components/PopInput/PopInput.jsx
 @ ./mxcube3/ui/containers/BeamlineSetupContainer.jsx
 @ ./mxcube3/ui/containers/SampleViewContainer.js
 @ ./mxcube3/ui/main.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8090 main.jsx
webpack: Failed to compile.
```

**Comment by mguijarr** [comment]
I use npm 3.1.10.

I use nvm to manage node/npm versions. Give it a try, it's a nice tool.

**Comment by meguiraun** [comment]
ok. It looks there is an issue with my npm version in my docker container and my version in mac (I share the folder), but I was not having any issue before. I hope updating my docker npm will solve the issue but we need to update the wiki with the minimum working version.

However I see a few things:
* Cannot create a manual sample, Action appears in the log but the panel is not displayed
* Tasks added in the sample grid appears as 'P-1'in the task list (the task name), but as 'P1' if they are added through current queue (in datacollection view) (minor name mismatch)
* Is the InOut switch changed again?
* There is no filename extension in the add task modal ('???')
* In dc task modal cannot 'show more' in the Processing section
* Cannot create an helical collection, Action appears in the log but the panel is not displayed

I will keep testing, thanks for this huge and painful work!

**Comment by mguijarr** [comment]
Thanks for the tests Mikel, we are also doing ours... The good thing is that we are not finding the same bugs ;)
So:
- we will have a look to the manual sample
- will fix the name mismatch
- yes it changed again :) it will change again probably ; latest idea is: the popover 'dialog' to open/close could appear when mouse hovers over the inout switch, thus not requiring one more click ; if it doesn't look great personally I preferred the previous design (with the button). What do you guys prefer?
- filename extension: in fact, the extension depends on the detector so it's more complicated - before we just had '.cbf' but Eiger is producing '.h5' for example... So for now I put '???', we can add an issue on this one
- there is nothing in the Processing section because I realized some fields were displayed, whereas it contained wrong data (like space groups), so I removed everything for now
- we will have a look for the helical collection

So, I am going to WIP this PR again - more news later. Meanwhile if you find something else or if you want to submit a bug fix don't hesitate ;)

Indeed it was *very* painful. Redux-form was the more difficult.

By the way: did you notice the refactoring of Login ?

**Comment by meguiraun** [comment]
Thanks, I will also continue testing and see if I can understand the changes in code.
I did not notice the login changes because I login automatically... gonna check

I do not have string opinion with the InOut switch, maybe I prefer this one a bit more since it takes less vertical space but I like less the popup (argggh... cannot choose!), but I let our scientist the word.

**Comment by meguiraun** [comment]
More than one will kill us if we remove the 'run now' button from the task, it missing

**Comment by mguijarr** [comment]
For the run now button, I removed it at some point because I was struggling with handleSubmit, I will add it back.

**Comment by mguijarr** [comment]
I think it's ready again. The missing things (file extension, missing fields) will go to new issues.

**Comment by meguiraun** [comment]
Almost there!
* helical line number does not reflect the _real_ line number/name, which in the following case is _L0_
image
* Adding a manual sample still does not work; when clicking on 'add' or 'addAndMount' I get 
_Cannot read property 'sampleName' of undefined_ in 
```
    let prefix = this.props.values.sampleName ? this.props.values.sampleName : 'noname';
```
`this.props.values` is empty, I tried to play a bit with the redux-form but it is probably faster if you fix this.

**Comment by marcus-oscarsson** [comment]
Hey !

Okey, I have added a fix for the helical line number. I'm wondering a bit why lines and points start at different counts. Could we fix that so that everything starts from 1 ?.

Marcus

**Comment by meguiraun** [comment]
I do not mind to leave the unified starting number to a future issue.

**Comment by meguiraun** [comment]
Thanks a lot guys for all this huge work!!

**Pull request merged**
