### PR TITLE
Beamline setup

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Good evening,

(PLEASE NOTE: Make sure to merge the fixes #203  and logging_fixes #204  before merging this !) 

Sorry for this somewhat late PR, it took some time to get the things in order on the beamline. In anyways we have done the wiring to connect resolution, transmission, energy and fast shutter to actual hardware. Its been tested here at ID 30a3 during the afternoon. We also took the opportunity to improve some of the internal API's (using the states defined by the abstract motor object). And also, of course squishing some bugs :).

The value changes/updates are now sent over the hwr namespace removing some unnecessary code. We experienced some problems with the code in socketIO.js in the handler:

` socketHWR.on('Motors', (record) => {`

We didn't receive any updates if that code was running so we commented it and replaced it with a console.log. We noticed that you already had commented out big parts of that code, did you experience something similar ?

The beamstop and safety shutter still remain to be done, I will try to finish them this evening or tomorrow morning. I wanted share the current work done to ease the integration work for you guys. The safety-shutter and beamstop are very similar to the fast-shutter so it should be fairly fast to finish up.

Regards,
Marcus and Matias

### CODE REVIEW

**Comment by meguiraun** [comment]
hej,
Thanks for this great work!
You should still receive "Motor" messages through the socketio, they are originating [here] (https://github.com/mxcube/mxcube3/blob/master/mxcube3/routes/signals.py#L104). Whenever a motor moves, a new message is received (with all the motors position in the dict, for simplicity). Then, the client updates the motor input fields accordingly. Have you tried to move any motor to see if a message is triggered?

**Comment by marcus-oscarsson** [comment]
Hej Mikel,

The motor actions/movement are triggered but we didn't get any intermediate state or values from the motors. I have to admit that we didn't dig too far since we were quite limited in time. However we didn't get any other events to work if that particular code was running which we found really strange. We didn't investigate it further because we wanted to finish the beamline-setup work. We were hoping that maybe you already had some idea of what it could be :). I can investigate it a bit more when Ive finished the last part of the bemline-setup.

**Comment by meguiraun** [comment]
That part has been working for us, although we have seen some weird issues with some messages not being sent. We can have a look ourselves when we test this pr.

**Comment by bolmsten** [comment]
@marcus-oscarsson @mguijarr  Can you solve the merge conflicts that now exists after merging the other PRs

**Comment by marcus-oscarsson** [comment]
Hey Guys !,

So the merge conflicts are solved, with the help of some git magic from Matias :) 

We've added the beamstop and safetyshutter, we don't have capillary on our beamline here
but I've added some "template" code to make it easier for you to add. Just un-comment the lines related to capillary in ho_mediators/beamline_setup.py starting at line 93.

`capillary = self.getObjectByRole("capillary")`

You will of-course also need to add the necessary information in the xml files mainly 
beamline-setup.xml.

The switch control did not really provide the flexibility we wanted, its especially lacking some
callbacks. So we have replaced it with a custom control. The new control consists of two buttons and a div to display the status.

Cheers,
Marcus

**Pull request merged**
