### PR TITLE
Deep copy

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hey !

A very simple fix for issue #340, an alternative would be to use the node package [deepcopy](https://www.npmjs.com/package/deepcopy) or other similar solution. A third option could also be to use immuatable js as suggested by Fredrik. This should
however solve the problem for the time being. 

I know its maybe not the fastest way but I think it works well enough.

Marcus

### CODE REVIEW

**Comment by bolmsten** [comment]
Have you tested this solution? For me it still does not work.

**Comment by marcus-oscarsson** [comment]
Of-course, what is it that does not work ?.

**Comment by bolmsten** [comment]
If you look at the log before and after you add a task you will see the task is already their in the before.

**Comment by marcus-oscarsson** [comment]
I see, you are right but I'm not sure that the line you identified is the source of the problem because the
deep copy routine works. So it has to be something else, ill try to see if I can find the actual source of this problem.

**Comment by marcus-oscarsson** [comment]
So I found the problem, the problem was actually [line 188](https://github.com/mxcube/mxcube3/blob/master/mxcube3/ui/reducers/queue.js#L188).

I don't know why but I assumed that spread and Object.assign did a deep copy which is not the case. Its clearly stated in the Object.assign documentation:
```
    Warning for Deep Clone
    For deep cloning, we need to use other alternatives. This is because Object.assign() copies the 
    property  reference when the property being assigned is an object.
```
So actually we only copied the references. Actually we do still have a problem with the Array.from code
but it only shows when doing update. Since we otherwise only add and delete references. Ill take a quick look to see if there are more places to update.

Cheers,
Marcus

**Comment by marcus-oscarsson** [comment]
So I'm using the deepCopy routine where I believe its needed, Its possible that I have missed to change in some places and I have only updated the queue reducer. This problem basically only occurs when we have key value pairs where the value is a reference which is, correct me if Im wrong, in the queue and the sample list.

**Comment by bolmsten** [comment]
`      const queue = {
        ...state.queue,
        [sampleID]: {
          ...state.queue[sampleID],
          tasks: [
            ...state.queue[sampleID].tasks,
            action.task
          ]
        }
      };

      const displayData = {
        ...state.displayData,
        [sampleID]: {
          ...state.displayData[sampleID],
          tasks: [
            ...state.displayData[sampleID].tasks,
            { collapsed: false, state: 0 }
          ]
        }
      };`

**Comment by bolmsten** [comment]
`
      const queue = {
        ...state.queue,
        [sampleID]: {
          ...state.queue[sampleID],
          tasks: [
            ...state.queue[sampleID].tasks,
            action.task
          ]
        }
      };

      const displayData = {
        ...state.displayData,
        [sampleID]: {
          ...state.displayData[sampleID],
          tasks: [
            ...state.displayData[sampleID].tasks,
            { collapsed: false, state: 0 }
          ]
        }
      };
`

**Comment by bolmsten** [comment]
const queue = {
        ...state.queue,
        [sampleID]: {
          ...state.queue[sampleID],
          tasks: [
            ...state.queue[sampleID].tasks,
            action.task
          ]
        }
      };

      const displayData = {
        ...state.displayData,
        [sampleID]: {
          ...state.displayData[sampleID],
          tasks: [
            ...state.displayData[sampleID].tasks,
            { collapsed: false, state: 0 }
          ]
        }
      };

**Comment by bolmsten** [comment]
A bit of code showing how to copy only the part of the queue that is changed

**Comment by marcus-oscarsson** [comment]
Thanks for the code,

Ive have applied the principle used in the snippet to replace the clone call. The clone packages
has also been removed. 

Cheers,
Marcus

**Pull request merged**
